# Netlify configuration file

[build]
  publish = "."
  command = ""

[[plugins]]
package = "@netlify/plugin-sitemap"

# Global headers for XML files
[[headers]]
  for = "*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

# Specific headers for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "no-cache"

# Handle XML files
[[redirects]]
  from = "/*.xml"
  to = "/:splat"
  status = 200
  force = true
  
[build.processing]
  skip_processing = false
